---
- name: install tomcat server
  hosts: webserver
  become: true

  tasks:
  - name: install java
    yum: 
      name: java
      state: latest

  - name: download tomcat server packages
    get_url:
      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.46/bin/apache-tomcat-8.5.46.tar.gz -P /usr/local
      dest: /usr/local

  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-8.5.46.tar.gz 
      dest: /usr/local
      remote_src: yes

  - name: start tomcar services
    shell: nohup /usr/local/apache-tomcat-8.5.46/bin/start.sh
